#! /usr/bin/env python
import sys

from optparse import OptionParser

from modules.hosts import get_host_analyzer
from modules.summary import full_summary

def opts() :
    parser = OptionParser("usage: %prog [options]")
    parser.add_option("--local-debug", dest="local_debug",
                      default=None, metavar="Q",
                      help="use text files instead of calling status commands")
    parser.add_option("--watch", dest="watch", default=None, metavar="N",
                      type="int", help="show status every N seconds")
    options,args = parser.parse_args()
    return options, args


def watch_queues(analyzer,delay):
    import time
    try:
        while True:
            time.sleep(delay)
            full_summary(analyzer)
    except KeyboardInterrupt:
        exit()


if __name__=="__main__":
    options, args = opts()
    HostQAnalyzer = get_host_analyzer()
    QAnalyzer = HostQAnalyzer()
    repeat = (options.watch is not None)
    full_summary(QAnalyzer)
    if repeat:
        watch_queues(QAnalyzer,options.watch)
