#! /usr/bin/env python
import sys
from queues.sgejobanalyzer import SGEJobAnalyzer
from getpass  import getuser

def print_user_job_count(analyzer, users, title=False, output_format = None, pl = None):
    if output_format == None :
        output_format = "{u:<8} {r:>8} {q:>8} {o:>8}"
        pl = 35

    sub_banner= "="*pl
    banner = "-"*pl
    if title :
        print banner
    print output_format.format(u="", r="Running", q="Queued", o="Other")
    print sub_banner
    for user in users :
        running, queued, other = analyzer.get_user_job_counts(user)
        print output_format.format(u=user, r=running, q=queued, o=other)
    if title :
        print banner

def print_queue_status(analyzer, output_format = None, pl = None) :
    output_format = "{q:<12} {a:>8} {t:>8}"
    q_dict = analyzer.get_queue_status()
    for q, cores in q_dict.iteritems() :
        print output_format.format(q=q, a=cores['a'], t=cores['t'])

if __name__=="__main__":
    userlist =[]
    if len(sys.argv) > 1 :
        userlist = sys.argv[1:] 
    else :
        userlist = [getuser()]
    test_analyzer = SGEJobAnalyzer()
    print_user_job_count(test_analyzer, userlist, title=True)
    print_queue_status(test_analyzer)
