#! /usr/bin/env python
import sys
from queues.sgejobanalyzer import SGEJobAnalyzer
from getpass  import getuser

def per_user_summary(analyzer, title=False, output_format = None, pl = None):
    if output_format == None :
        output_format = "{u:<10}",
        output_banner ="{:=^10}".format("")
        per_queue_format = "{r:>5},{q:>5},{o:>5}"

    print output_banner
    print output_format.format(u="", r="Running", q="Queued", o="Other")
    print sub_banner
    u_dict = analyzer.get_queue_job_counts()
    print u_dict
    #print output_format.format(u=user, r=running, q=queued, o=other)
    if title :
        print banner

def per_queue_summary(analyzer, output_format = None, pl = None) :
    output_format = "{q:<12} {a:>8} {t:>8}"
    q_dict = analyzer.get_queue_status()
    for q, cores in q_dict.iteritems() :
        print output_format.format(q=q, a=cores['a'], t=cores['t'])

if __name__=="__main__":
    userlist =[]
    test_analyzer = SGEJobAnalyzer()
    per_user_summary(test_analyzer, title=True)
    per_queue_summary(test_analyzer)
